### ISSUE TITLE
bounding box mode with YOLOv8 does not work when using NPU accelerator

### ISSUE THREAD

**Issue by thile732** [nnstreamer/nnstreamer#4416] opened 2024-02-28 08:17 UTC
Hi everybody
I am trying to run yolov8 with nnstreamer library on imx8mp board
I followed the following link to run command:
https://github.com/nnstreamer/nnstreamer/commit/dabaadc553766beff030d13d393aec0477a1dba0

command is as follows:
gst-launch-1.0 v4l2src device=/dev/video2 ! imxvideoconvert_g2d ! videoscale ! videoconvert ! video/x-raw,width=320,height=320,format=RGB,framerate=30/1,pixel-aspect-ratio=1/1 ! tee name=t t. ! queue ! tensor_converter ! other/tensors,num_tensors=1,types=uint8,format=static,dimensions=3:320:320:1 ! tensor_transform mode=arithmetic option=typecast:float32,add:0.0,div:255.0 ! queue leaky=2 max-size-buffers=2 ! tensor_filter framework=tensorflow2-lite model=yolov8s_float16.tflite custom=Delegate:XNNPACK,NumThreads:4 latency=1 ! other/tensors,num_tensors=1,types=float32,format=static,dimensions=2100:84:1 ! tensor_transform mode=transpose option=1:0:2:3 ! tensor_decoder mode=bounding_boxes option1=yolov8 option2=coco-80.txt option4=320:320 option5=320:320 ! video/x-raw,width=320,height=320,format=RGBA ! mix.sink_0 t. ! queue ! mix.sink_1 compositor name=mix sink_0::zorder=2 sink_1::zorder=1 ! videoconvert ! autovideosink

It worked with the output being that the image had its bounding box drawn
I then tried using the NPU accelerator as follows:
gst-launch-1.0 v4l2src device=/dev/video2 ! imxvideoconvert_g2d ! videoscale ! videoconvert ! video/x-raw,width=320,height=320,format=RGB,framerate=30/1,pixel-aspect-ratio=1/1 ! tee name=t t. ! queue ! tensor_converter ! other/tensors,num_tensors=1,types=uint8,format=static,dimensions=3:320:320:1 ! tensor_transform mode=arithmetic option=typecast:float32,add:0.0,div:255.0 ! queue leaky=2 max-size-buffers=2 ! tensor_filter framework=tensorflow2-lite model=yolov8s_float16.tflite **accelerator=true:npu custom=Delegate:External,ExtDelegateLib:libvx_delegate.so** latency=1 ! other/tensors,num_tensors=1,types=float32,format=static,dimensions=2100:84:1 ! tensor_transform mode=transpose option=1:0:2:3 ! tensor_decoder mode=bounding_boxes option1=yolov8 option2=coco-80.txt option4=320:320 option5=320:320 ! video/x-raw,width=320,height=320,format=RGBA ! mix.sink_0 t. ! queue ! mix.sink_1 compositor name=mix **sink_0::zorder=2** sink_1::zorder=1 ! videoconvert ! autovideosink

However the output only includes the image without the bounding box, I also get no error log at all. Am I missing something? Greatly appreciate the advice. Thanks!

**Comment by myungjoo** [comment] 2024-02-28 10:24
Debugging Advices:
1. Try a minimal code that recreates the issue.
2. Check warning messages. How-to: https://gstreamer.freedesktop.org/documentation/tutorials/basic/debugging-tools.html?gi-language=c
3. Check if ```libvx_delegate.so``` is properly loaded by tensorflow2-lite subplugin.
    - Unfortunately, the related code is not handling exceptions properly. You will need to check them manually with debuggers or by inserting a few log-print lines; i.e., it does not check if the ```delegate``` object is properly created: https://github.com/nnstreamer/nnstreamer/blob/ec3fdde2ae03e5b5065bf675ff1f2560c9e57db5/ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc#L522-L553

**Comment by thile723** [comment] 2024-02-29 04:28
Thanks for replying
I tried adding a few lines of command to print the log as follows:

```
case TFLITE_DELEGATE_EXTERNAL:
      {
#ifdef TFLITE_EXTERNAL_DELEGATE_SUPPORTED
        TfLiteExternalDelegateOptions options;

        options = TfLiteExternalDelegateOptionsDefault (ext_delegate_path);

        /* Add optional key values to delegate configuration */
        if (ext_delegate_kv_table) {
          GHashTable *table = ext_delegate_kv_table;
          GHashTableIter iter;
          gchar *key, *value;

          g_hash_table_iter_init (&iter, table);
          while (g_hash_table_iter_next (&iter, (gpointer *) &key, (gpointer *) &value))
            options.insert (&options, key, value);
        }

        delegate = TfLiteExternalDelegateCreate (&options);
        void (*deleter) (TfLiteDelegate *) = [] (TfLiteDelegate *delegate_) {
          TfLiteExternalDelegateDelete (delegate_);
        };

        setDelegate (delegate, deleter);
        ml_logw ("External delegate is supported.");
#else
        ml_logw ("NNStreamer was built without external delegate. Given delegate option external is ignored.");
#endif
        break;
      }
    default:
      break;
  }

  delegate = getDelegate ();
  if (delegate != nullptr) {
    if (interpreter->ModifyGraphWithDelegate (delegate) != kTfLiteOk) {
      ml_loge ("Failed to apply delegate\n");
      return -2;
    }
  }

  if (interpreter->AllocateTensors () != kTfLiteOk) {
    ml_loge ("Failed to allocate tensors\n");
    return -2;
  }
  ml_logw ("External delegate is supported. !!!");
```


When looking at the result log, it looks like the external delegate library was loaded successfully:

> ** Message: 05:11:42.982: accl = npu
> Vx delegate: allowed_cache_mode set to 0.
> Vx delegate: device num set to 0.
> Vx delegate: allowed_builtin_code set to 0.
> Vx delegate: error_during_init set to 0.
> Vx delegate: error_during_prepare set to 0.
> Vx delegate: error_during_invoke set to 0.
> 
> ** (gst-launch-1.0:3010): WARNING **: 05:11:42.998: External delegate is supported.
> 
> ** (gst-launch-1.0:3010): WARNING **: 05:11:43.000: External delegate is supported. !!!
> Setting pipeline to PAUSED ...
> Pipeline is live and does not need PREROLL ...
> Pipeline is PREROLLED ...
> Setting pipeline to PLAYING ...
> New clock: GstSystemClock
> [13727.179418] enter isp_mi_stop
> [13727.186545] imx415 2-001a: imx415_set_fps: 30720
> [13727.191185] imx415 2-001a: imx415_set_vmax: 2250
> [13727.201761] enter isp_s_comp
> [13727.204673] enter isp_s_comp
> [13727.207567] enter isp_s_comp
> [13727.230851] enter wdr3_hw_init
> [13727.233920] wdr3 res: 3840 2160
> [13727.261650] enter isp_set_stream 1
> [13727.276373] enter isp_mi_start
> Redistribute latency...
> Redistribute latency...
> W [HandleLayoutInfer:278]Op 162: default layout inference pass.
> W [HandleLayoutInfer:278]Op 162: default layout inference pass.
> W [HandleLayoutInfer:278]Op 162: default layout inference pass.
> W [HandleLayoutInfer:278]Op 162: default layout inference pass.
> W [HandleLayoutInfer:278]Op 162: default layout inference pass.
> W [HandleLayoutInfer:278]Op 162: default layout inference pass.
> [13782.617254] ###### video2(0) 30.00 fps ######
> [13813.283917] ###### video2(0) 30.00 fps ######
> [13843.950600] ###### video2(0) 30.00 fps ######

If I add GST_DEBUG=2 to the statement, this is what the log is all about:

> ** Message: 05:22:30.675: accl = npu
> Vx delegate: allowed_cache_mode set to 0.
> Vx delegate: device num set to 0.
> Vx delegate: allowed_builtin_code set to 0.
> Vx delegate: error_during_init set to 0.
> Vx delegate: error_during_prepare set to 0.
> Vx delegate: error_during_invoke set to 0.
> 
> ** (gst-launch-1.0:3062): WARNING **: 05:22:30.690: External delegate is supported.
> 
> ** (gst-launch-1.0:3062): WARNING **: 05:22:30.692: External delegate is supported. !!!
> Setting pipeline to PAUSED ...
> 0:00:00.489182250 3062 0xaaaaf4ac1cc0 WARN v4l2src gstv4l2src.c:794:gst_v4l2src_query:<v4l2src0> Can't give latency since framerate isn't fixed !
> 0:00:00.489330375 3062 0xaaaaf4ac1cc0 WARN v4l2src gstv4l2src.c:794:gst_v4l2src_query:<v4l2src0> Can't give latency since framerate isn't fixed !
> 0:00:00.489386000 3062 0xaaaaf4ac1cc0 WARN aggregator gstaggregator.c:2099:gst_aggregator_query_latency_unlocked:<mix> Latency query failed
> Pipeline is live and does not need PREROLL ...
> 0:00:00.490113375 3062 0xaaaaf4ac1cc0 WARN v4l2src gstv4l2src.c:794:gst_v4l2src_query:<v4l2src0> Can't give latency since framerate isn't fixed !
> 0:00:00.490259250 3062 0xaaaaf4ac1cc0 WARN v4l2src gstv4l2src.c:794:gst_v4l2src_query:<v4l2src0> Can't give latency since framerate isn't fixed !
> 0:00:00.490311750 3062 0xaaaaf4ac1cc0 WARN aggregator gstaggregator.c:2099:gst_aggregator_query_latency_unlocked:<mix> Latency query failed
> 0:00:00.490373250 3062 0xaaaaf4ac1cc0 WARN v4l2src gstv4l2src.c:794:gst_v4l2src_query:<v4l2src0> Can't give latency since framerate isn't fixed !
> 0:00:00.490434875 3062 0xaaaaf4ac1cc0 WARN v4l2src gstv4l2src.c:794:gst_v4l2src_query:<v4l2src0> Can't give latency since framerate isn't fixed !
> 0:00:00.490469125 3062 0xaaaaf4ac1cc0 WARN aggregator gstaggregator.c:2099:gst_aggregator_query_latency_unlocked:<mix> Latency query failed
> Pipeline is PREROLLED ...
> Setting pipeline to PLAYING ...
> 0:00:00.491536750 3062 0xaaaaf4ac1cc0 WARN v4l2src gstv4l2src.c:794:gst_v4l2src_query:<v4l2src0> Can't give latency since framerate isn't fixed !
> 0:00:00.491637125 3062 0xaaaaf4ac1cc0 WARN v4l2src gstv4l2src.c:794:gst_v4l2src_query:<v4l2src0> Can't give latency since framerate isn't fixed !
> 0:00:00.491675375 3062 0xaaaaf4ac1cc0 WARN aggregator gstaggregator.c:2099:gst_aggregator_query_latency_unlocked:<mix> Latency query failed
> New clock: GstSystemClock
> 0:00:00.708563375 3062 0xaaaaf4ac1cc0 WARN v4l2src gstv4l2src.c:794:gst_v4l2src_query:<v4l2src0> Can't give latency since framerate isn't fixed !
> 0:00:00.708659125 3062 0xaaaaf4ac1cc0 WARN v4l2src gstv4l2src.c:794:gst_v4l2src_query:<v4l2src0> Can't give latency since framerate isn't fixed !
> 0:00:00.708694000 3062 0xaaaaf4ac1cc0 WARN aggregator gstaggregator.c:2099:gst_aggregator_query_latency_unlocked:<mix> Latency query failed
> 0:00:00.717675000 3062 0xaaaaf4ac1cc0 WARN [14374.880286] enter isp_mi_stop
> v4l2src gstv4l2src.c:794:gst_v4l2src_query:<v4l2src
> 0:00:00.717781750  3062 0xaaaaf4ac1cc0 WARN          [14374.909875] enter isp_s_comp
>        v4l2src gstv4l2src.c:794:g[14374.914755] enter isp_s_comp
> st_v4l2src_query:<v4l2src0> [14374.920506] enter isp_s_comp
> Can't give latency since framerate isn't fixated !
> 0:00:00.717817000  3062 0xaaaaf4ac1cc0 WARN              aggregator gstagg[14374.938908] enter wdr3_hw_init
> regator.c:2099:gst_aggregator_que[14374.942906] wdr3 res: 3840 2160
> ry_latency_unlocked:<mix> Latency query failed
> [14374.973086] enter isp_set_stream 1
> [14374.987851] enter isp_mi_start
> Redistribute latency...
> 0:00:01.003242750  3062 0xaaaaf4ac1cc0 WARN             waylandsink wlwindow.c:439:gst_wl_window_new_internal: init surface_state fail, fallback to scale=1 fullscreen (1024x736)
> Redistribute latency...
> W [HandleLayoutInfer:278]Op 162: default layout inference pass.
> W [HandleLayoutInfer:278]Op 162: default layout inference pass.
> W [HandleLayoutInfer:278]Op 162: default layout inference pass.
> W [HandleLayoutInfer:278]Op 162: default layout inference pass.
> W [HandleLayoutInfer:278]Op 162: default layout inference pass.
> W [HandleLayoutInfer:278]Op 162: default layout inference pass.
> [14433.392592] ###### video2(0) 30.00 fps ######
> [14464.059253] ###### video2(0) 30.00 fps ######

ADDITIONAL:
I tested the detection using mobilenet_ssd_v2_coco_quant_postprocess.tflite model on python script using Delegate:External,ExtDelegateLib:libvx_delegate.so and it worked fine

> python3 nndetection.py /dev/video2 NPU /home/root/.cache/demoexperience/mobilenet_ssd_v2_coco_quant_postprocess.tflite /home/root/.cache/demoexperience/coco_labels.txt
> INFO:root:finished to load labels, total [90]
> /home/root/nndetection.py:89: PyGIDeprecationWarning: Since version 3.11, calling threads_init is no longer needed. See: https://wiki.gnome.org/PyGObject/Threading
>   GObject.threads_init()
> /home/root/nndetection.py:115: PyGIDeprecationWarning: GObject.MainLoop is deprecated; use GLib.MainLoop instead
>   self.loop = GObject.MainLoop()
> [15168.319614] enter isp_mi_stop
> ** Message: 05:35:44.725: accl = npu
> Vx delegate: allowed_cache_mode set to 0.
> Vx delegate: device num set to 0.
> Vx delegate: allowed_builtin_code set to 0.
> Vx delegate: error_during_init set to 0.
> Vx delegate: error_during_prepare set to 0.
> Vx delegate: error_during_invoke set to 0.
> 
> ** (python3:3123): WARNING **: 05:35:44.802: External delegate is supported.
> WARNING: Fallback unsupported op 32 to TfLite
> 
> ** (python3:3123): WARNING **: 05:35:44.805: External delegate is supported. !!!
> INFO:root:received start message
> [15168.979373] enter isp_mi_stop
> [15168.986494] imx415 2-001a: imx415_set_fps: 30720
> [15168.991145] imx415 2-001a: imx415_set_vmax: 2250
> [15169.001686] enter isp_s_comp
> [15169.004613] enter isp_s_comp
> [15169.007509] enter isp_s_comp
> [15169.026845] enter wdr3_hw_init
> [15169.029912] wdr3 res: 3840 2160
> [15169.056881] enter isp_set_stream 1
> [15169.071522] enter isp_mi_start
> W [HandleLayoutInfer:278]Op 162: default layout inference pass.
> W [HandleLayoutInfer:278]Op 162: default layout inference pass.
> W [HandleLayoutInfer:278]Op 162: default layout inference pass.
> W [HandleLayoutInfer:278]Op 162: default layout inference pass.
> W [HandleLayoutInfer:278]Op 162: default layout inference pass.
> W [HandleLayoutInfer:278]Op 162: default layout inference pass.
> W [HandleLayoutInfer:278]Op 162: default layout inference pass.
> W [HandleLayoutInfer:278]Op 162: default layout inference pass.
> W [HandleLayoutInfer:278]Op 162: default layout inference pass.
> W [HandleLayoutInfer:278]Op 162: default layout inference pass.
> W [HandleLayoutInfer:278]Op 162: default layout inference pass.
> W [HandleLayoutInfer:278]Op 162: default layout inference pass.
> W [HandleLayoutInfer:278]Op 162: default layout inference pass.

**Comment by thile723** [comment] 2024-02-29 08:39
I found that using NPU acceleration mode was effective. However, while inference time without NPU acceleration is ~2-3 seconds/1 frame, inference time with NPU acceleration is ~20-30 seconds/1 frame. It's so weird.

**Comment by myungjoo** [comment] 2024-03-04 01:36
Because I have never put my hands on NXP's NPUs, I cannot be sure on its actual behaviors.
However, in general, NPUs, especially those in embedded devices, target specific neural network operators and structure.

Thus, if Yolo-v8's architecture or operators have not been the optimization targets when this iMX NPU was designed, this slow-down is not too weird. Similar things happen with transformers in most embedded NPUs except for those powerful NPUs in flagship mobile phones/tablets/laptops.

**Comment by NihalAbdulRazack** [comment] 2024-09-20 11:45
rishad@ghost:~$ gst-launch-1.0 v4l2src ! videoconvert ! videoscale ! \
video/x-raw,width=320,height=320,format=RGB,pixel-aspect-ratio=1/1,framerate=30/1 ! tee name=t \
t. ! queue ! tensor_converter ! other/tensors,num_tensors=1,types=uint8,format=static,dimensions=3:320:320:1 ! \
tensor_transform mode=arithmetic option=typecast:float32,add:0.0,div:255.0 ! \
queue leaky=2 max-size-buffers=2 ! \
tensor_filter framework=tensorflow2-lite model=/home/rishad/NIhal/yolo/best_saved_model/best_float16.tflite custom=Delegate:XNNPACK,NumThreads:4 latency=1 ! \
other/tensors,num_tensors=1,types=float32,format=static,dimensions=2100:84:1 ! \
tensor_transform mode=transpose option=1:0:2:3 ! \
tensor_decoder mode=bounding_boxes option1=yolov8 option2=/home/rishad/NIhal/yolo/label.txt option3=0 option4=320:320 option5=320:320 ! \
video/x-raw,width=320,height=320,format=RGBA ! mix.sink_0 \
t. ! queue ! mix.sink_1 \
compositor name=mix sink_0::zorder=2 sink_1::zorder=1 ! videoconvert ! autovideosink
** Message: 17:13:40.792: accl = cpu

** (gst-launch-1.0:55221): WARNING **: 17:13:40.793: Input/output tensors should be memcpy-ed rather than explicitly assigning its ptr when XNNPACK Delegate is used.

** (gst-launch-1.0:55221): WARNING **: 17:13:40.793: This could cause performance degradation if sizes of input/output tensors are large
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.

** (gst-launch-1.0:55221): CRITICAL **: 17:13:40.834: Yolov8 bounding-box decoder accepts float32 input tensors only. The given input tensor is: Num_Tensors = 1, Tensors = [{"", (null), (null)}].

** (gst-launch-1.0:55221): CRITICAL **: 17:13:40.834: Yolov8 bounding-box decoder accepts float32 input tensors only. The given input tensor is: Num_Tensors = 1, Tensors = [{"", (null), (null)}].
WARNING: erroneous pipeline: could not link queue1 to tensorfilter0
Can you please explain what is the issue here and how to solve it , the model here is  custom model i trained using yolov8n and for label.txt it is in format 
1 withouthelmet
2 withhelmet

**Closed** 2024-10-21 09:48 UTC
Labels: question

**Comment by rajhlinux** [comment] 2025-01-17 23:36
> I found that using NPU acceleration mode was effective. However, while inference time without NPU acceleration is ~2-3 seconds/1 frame, inference time with NPU acceleration is ~20-30 seconds/1 frame. It's so weird. But this problem only happens for yolov8 model, when i test with mobilenet-ssd model everything works fine.

Sounds like the model algo is not specifically optimized for NXP's NPU... you'll need to perform clever post and pre processing as well to greatly increase FPS during inference. 

Not sue if your NXP module has GPU hardware built in, you'd want to use that for post and pre processing and let the NPU take care only on the inference part. The CPU should most likely just copy data in and out and make sure the CPU does not perform any calculations. Depending on what decoding and encoding of media stream source, sometimes CPU might be better in some cases for decoding/encoding. Specially if it is a multi-CPU with Multi-core for each CPU.  Need to figure these things out first to get max FPS.

Also export the model from ultralytics using various optimized features. Have you tried using INT8 export instead of FP16/32?
