### ISSUE TITLE
Possible to concat video streams in the 'batch' dimension?

### ISSUE THREAD

**Issue by KurtKoo** [nnstreamer/nnstreamer#3854] opened 2022-07-27 10:14 UTC
Thanks for your great work.

Is it possible to concat video streams in the 'batch' dimension with currently available plugins? For example, concat four video streams(1x3x480x640) in the 'batch' dimension, outputing one video stream(4x3x480x640).

We tried 'tensor_mux', 'tensor_merge'(this should work, however its merge-mode doesn't look like what we need) and 'tensor_aggregator', but they didn't work as we hope and we can't figure out how to achieve it with plugins above.

If plugins above are able to reach the goal, would you please give any script as examples?

Thank you!

**Comment by KurtKoo** [comment] 2022-07-28 01:58
> The `tensor_aggregator` is for such cases, e.g., aggregating recent 4 frames of video as a single frame for an LSTM-like network.
> 
> What are the GSTCAPs of the "input" and the "output? E.g., `other/tensors,num_tensors=1,dimensions=640:480:3` and `other/tensors,num_tensors=1,dimensions=640:480:3:4`.
> 
> According to https://github.com/nnstreamer/nnstreamer/blob/main/gst/nnstreamer/elements/gsttensor_aggregator.md , for that example, you need `tensor_aggregator frames-in=1 frames-out=4 frames-flush=4 frames-dim=3`. @jijoongmoon is this right?
> 
> Also, the pipeline example in the above link does something similar to your description.

Thanks for your reply!

I learned the usage of 'tensor_aggregator' by reading the documents and checking the command output of 'gst-inspect-1.0 tensor_aggregator'. It looks like your example(other/tensors,num_tensors=1,dimensions=640:480:3 and other/tensors,num_tensors=1,dimensions=640:480:3:4) is forming a tensor from '**one input video stream**'.

However, I am looking forward to forming one tensor from '**four input video stream**' so that the pipeline is able to run batch-processing.

Is it possible to achieve this with 'tensor_aggregator'？Or some other plugins?

Thanks!

**Comment by KurtKoo** [comment] 2022-07-28 03:42
I tried a new solution but it didn't work successfully.

Supposing there are 4 input video stream,
with 'tensor_mux' creating 1 output video stream(according to the source code, it should be 4 GstMemory contained in 1 GstBuffer),
'tensor_aggregator' receives the output from 'tensor_mux' and shapes the tensor like 640:480:3:4.

However, it didn't work maybe because the src_caps of 'tensor_mux' is 'other/tensors, num-tensors=3' and the sink_caps of 'tensor_aggregator' is fixed to 'other/tensors, num-tensors=1'.

Is that correct? 
Is there any currently available plugins in NNStreamer able to concat multiple input stream in the 'batch' dimension?
Or write a new plugin?

Thank you!

**Comment by myungjoo** [comment] 2022-07-28 08:00
If you have 4 input video streams, ```tensor_merge``` can create ```other/tensors,num_tensors=1,dimensions=640:480:3:4```.
On the other hand, ```tensor_mux``` can create a ```other/tensors,num_tensors=4,dimensions=640:480:3,640:480:3,640:480:3,640:480:3```.

Please refer to https://arxiv.org/pdf/2101.06371.pdf Chapter III. 

You need to be careful with synchronization policy.

**Comment by KurtKoo** [comment] 2022-07-28 11:32
Oops I missed the other desriptions about the 'options' of 'tensor_merge'.

I tested it with the **TensorRT sub-plugin** example(lenet5.uff) according to scripts in 'runTest.sh' file.
Get two corresponding input of 'tensor_converter', **'tensor_merge option=3'** them and go through the 'tensor_transform' as the script does. I end this pipeline with 'tensor_sink' and it works. The input of 'tensor_sink' should be **28:28:1:2**, right?

Here comes another problem.How to define the properties of 'tensor_filter'?
The 'input' is **28:28:1** and 'output' is **10**.
I failed so many times. I found that, when I set the 'input=56:56:1', it outputs as below:
`(gst-launch-1.0:22131): GLib-CRITICAL **: 19:26:33.919: g_string_insert_len: assertion 'len == 0 || val != NULL' failed

(gst-launch-1.0:22131): GLib-CRITICAL **: 19:26:33.920: g_string_insert_len: assertion 'len == 0 || val != NULL' failed

(gst-launch-1.0:22131): GLib-CRITICAL **: 19:26:33.921: g_string_insert_len: assertion 'len == 0 || val != NULL' failed

** (gst-launch-1.0:22131): CRITICAL **: 19:26:35.255: UffParser: Parser error: reshape1: Reshape: Volume mismatch. Note: Initial Volume = 6050, New Volume = 800

** (gst-launch-1.0:22131): CRITICAL **: 19:26:35.255: Network must have at least one output

** (gst-launch-1.0:22131): CRITICAL **: 19:26:35.255: Network validation failed.

** (gst-launch-1.0:22131): CRITICAL **: 19:26:35.255: Failed to create the TensorRT Engine object

** (gst-launch-1.0:22131): CRITICAL **: 19:26:35.255: Failed to build a TensorRT engine

** (gst-launch-1.0:22131): CRITICAL **: 19:26:35.255: Failed to build a TensorRT engine

(gst-launch-1.0:22131): GLib-CRITICAL **: 19:26:35.256: g_string_insert_len: assertion 'len == 0 || val != NULL' failed

** (gst-launch-1.0:22131): CRITICAL **: 19:26:35.260: UffParser: Parser error: reshape1: Reshape: Volume mismatch. Note: Initial Volume = 6050, New Volume = 800

** (gst-launch-1.0:22131): CRITICAL **: 19:26:35.260: Network must have at least one output

** (gst-launch-1.0:22131): CRITICAL **: 19:26:35.260: Network validation failed.

** (gst-launch-1.0:22131): CRITICAL **: 19:26:35.261: Failed to create the TensorRT Engine object

** (gst-launch-1.0:22131): CRITICAL **: 19:26:35.261: Failed to build a TensorRT engine

** (gst-launch-1.0:22131): CRITICAL **: 19:26:35.261: Failed to build a TensorRT engine

(gst-launch-1.0:22131): GLib-CRITICAL **: 19:26:35.261: g_string_insert_len: assertion 'len == 0 || val != NULL' failed

** (gst-launch-1.0:22131): CRITICAL **: 19:26:35.265: UffParser: Parser error: reshape1: Reshape: Volume mismatch. Note: Initial Volume = 6050, New Volume = 800

** (gst-launch-1.0:22131): CRITICAL **: 19:26:35.266: Network must have at least one output

** (gst-launch-1.0:22131): CRITICAL **: 19:26:35.266: Network validation failed.

** (gst-launch-1.0:22131): CRITICAL **: 19:26:35.266: Failed to create the TensorRT Engine object

** (gst-launch-1.0:22131): CRITICAL **: 19:26:35.266: Failed to build a TensorRT engine

** (gst-launch-1.0:22131): CRITICAL **: 19:26:35.266: Failed to build a TensorRT engine

** (gst-launch-1.0:22131): WARNING **: 19:26:35.266: Given input info is invalid, cannot get output info.

(gst-launch-1.0:22131): GLib-CRITICAL **: 19:26:35.266: g_string_insert_len: assertion 'len == 0 || val != NULL' failed

** (gst-launch-1.0:22131): CRITICAL **: 19:26:35.273: UffParser: Parser error: reshape1: Reshape: Volume mismatch. Note: Initial Volume = 6050, New Volume = 800

** (gst-launch-1.0:22131): CRITICAL **: 19:26:35.273: Network must have at least one output

** (gst-launch-1.0:22131): CRITICAL **: 19:26:35.273: Network validation failed.

** (gst-launch-1.0:22131): CRITICAL **: 19:26:35.273: Failed to create the TensorRT Engine object

** (gst-launch-1.0:22131): CRITICAL **: 19:26:35.274: Failed to build a TensorRT engine

** (gst-launch-1.0:22131): CRITICAL **: 19:26:35.274: Failed to build a TensorRT engine

** (gst-launch-1.0:22131): WARNING **: 19:26:35.274: Given input info is invalid, cannot get output info.

(gst-launch-1.0:22131): GLib-CRITICAL **: 19:26:35.274: g_string_insert_len: assertion 'len == 0 || val != NULL' failed

** (gst-launch-1.0:22131): CRITICAL **: 19:26:35.279: UffParser: Parser error: reshape1: Reshape: Volume mismatch. Note: Initial Volume = 6050, New Volume = 800

** (gst-launch-1.0:22131): CRITICAL **: 19:26:35.279: Network must have at least one output

** (gst-launch-1.0:22131): CRITICAL **: 19:26:35.279: Network validation failed.

** (gst-launch-1.0:22131): CRITICAL **: 19:26:35.279: Failed to create the TensorRT Engine object

** (gst-launch-1.0:22131): CRITICAL **: 19:26:35.279: Failed to build a TensorRT engine

** (gst-launch-1.0:22131): CRITICAL **: 19:26:35.279: Failed to build a TensorRT engine

** (gst-launch-1.0:22131): WARNING **: 19:26:35.280: Given input info is invalid, cannot get output info.

** (gst-launch-1.0:22131): CRITICAL **: 19:26:35.280: il_getOutCaps: assertion 'dim[0] > 0 && dim[1] == 1' failed

(gst-launch-1.0:22131): GLib-CRITICAL **: 19:26:35.280: g_string_insert_len: assertion 'len == 0 || val != NULL' failed

** (gst-launch-1.0:22131): CRITICAL **: 19:26:35.284: UffParser: Parser error: reshape1: Reshape: Volume mismatch. Note: Initial Volume = 6050, New Volume = 800

** (gst-launch-1.0:22131): CRITICAL **: 19:26:35.285: Network must have at least one output

** (gst-launch-1.0:22131): CRITICAL **: 19:26:35.285: Network validation failed.

** (gst-launch-1.0:22131): CRITICAL **: 19:26:35.285: Failed to create the TensorRT Engine object

** (gst-launch-1.0:22131): CRITICAL **: 19:26:35.285: Failed to build a TensorRT engine

** (gst-launch-1.0:22131): CRITICAL **: 19:26:35.285: Failed to build a TensorRT engine

** (gst-launch-1.0:22131): WARNING **: 19:26:35.285: Given input info is invalid, cannot get output info.

** (gst-launch-1.0:22131): CRITICAL **: 19:26:35.285: il_getOutCaps: assertion 'dim[0] > 0 && dim[1] == 1' failed
Setting pipeline to PAUSED ...
Opening in BLOCKING MODE 
Opening in BLOCKING MODE 

** (gst-launch-1.0:22131): CRITICAL **: 19:26:35.307: UffParser: Parser error: reshape1: Reshape: Volume mismatch. Note: Initial Volume = 6050, New Volume = 800

** (gst-launch-1.0:22131): CRITICAL **: 19:26:35.307: Network must have at least one output

** (gst-launch-1.0:22131): CRITICAL **: 19:26:35.307: Network validation failed.

** (gst-launch-1.0:22131): CRITICAL **: 19:26:35.308: Failed to create the TensorRT Engine object

** (gst-launch-1.0:22131): CRITICAL **: 19:26:35.308: Failed to build a TensorRT engine

** (gst-launch-1.0:22131): CRITICAL **: 19:26:35.308: Failed to build a TensorRT engine
ERROR: Pipeline doesn't want to pause.
Setting pipeline to NULL ...
Freeing pipeline ...
`

Does the model cause the crash of pipeline? Or the 'tensor_filter' and 'tensor_decoder' part should be modified?
By the way, does the TensorRT sub-plugin support the batch-processing as we hope?

Thank you!

**Comment by myungjoo** [comment] 2022-07-29 00:07
> > If you have 4 input video streams, `tensor_merge` can create `other/tensors,num_tensors=1,dimensions=640:480:3:4`. On the other hand, `tensor_mux` can create a `other/tensors,num_tensors=4,dimensions=640:480:3,640:480:3,640:480:3,640:480:3`. You don't need `tensor_aggregator` if you have 4 input streams.
> > Please refer to https://arxiv.org/pdf/2101.06371.pdf Chapter III.
> > You need to be careful with synchronization policy.
> 
> Oops I missed the other desriptions about the 'options' of 'tensor_merge'.
> 
> I tested it with the **TensorRT sub-plugin** example(lenet5.uff) according to scripts in 'runTest.sh' file. Get two corresponding input of 'tensor_converter', **'tensor_merge option=3'** them and go through the 'tensor_transform' as the script does. I end this pipeline with 'tensor_sink' and it works. The input of 'tensor_sink' should be **28:28:1:2**, right?

Yes, that's right.

> 
> Here comes another problem.How to define the properties of 'tensor_filter'? The 'input' is **28:28:1** and 'output' is **10**. I failed so many times. I found that, when I set the 'input=**56:56:1**', it outputs as below: `(gst-launch-1.0:22131): GLib-CRITICAL **: 19:26:33.919: g_string_insert_len: assertion 'len == 0 || val != NULL' failed

Please show the minimal pipeline description that has the same error. (ref: https://stackoverflow.com/help/minimal-reproducible-example )

> 
> (gst-launch-1.0:22131): GLib-CRITICAL **: 19:26:33.920: g_string_insert_len: assertion 'len == 0 || val != NULL' failed
> 
> (gst-launch-1.0:22131): GLib-CRITICAL **: 19:26:33.921: g_string_insert_len: assertion 'len == 0 || val != NULL' failed
> 
> ** (gst-launch-1.0:22131): CRITICAL **: 19:26:35.255: UffParser: Parser error: reshape1: Reshape: Volume mismatch. Note: Initial Volume = 6050, New Volume = 800
> 
> ** (gst-launch-1.0:22131): CRITICAL **: 19:26:35.255: Network must have at least one output
> 
> ** (gst-launch-1.0:22131): CRITICAL **: 19:26:35.255: Network validation failed.
> 
> ** (gst-launch-1.0:22131): CRITICAL **: 19:26:35.255: Failed to create the TensorRT Engine object

Inferring only from this error message, it appears that you are using a model file that is not compatible with your tensorrt binary, or the given input dimension/output dimension (and types) are not compatible with your model file.

**Comment by KurtKoo** [comment] 2022-07-29 02:51
First of all, great gratitude for your solution about 'tensor_merge' and sorry about only listing the error log.

I tested based on the 'runTest.sh' of **TensorRT sub-plugin** . 
Images for test are '1.pgm' and '9.pgm' in 'nnstreamer/tests/test_models/data'.
Model for test are 'lenet5.uff' in 'nnstreamer/tests/test_models/models'.

Here is the script to reproduce:
**gst-launch-1.0 filesrc location=nnstreamer/tests/test_models/data/1.pgm ! image/x-portable-graymap,width=28,height=28,framerate=0/1 ! pnmdec ! video/x-raw,format=GRAY8 \
! tensor_converter input-type=uint8 \
! m.sink_0 filesrc location=nnstreamer/tests/test_models/data/9.pgm ! image/x-portable-graymap,width=28,height=28,framerate=0/1 ! pnmdec ! video/x-raw,format=GRAY8 \
! tensor_converter input-type=uint8 \
! m.sink_1 tensor_merge name=m mode=linear option=3 \
! tensor_transform mode=transpose option=1:2:0:3 ! tensor_transform mode=arithmetic option=typecast:float32,div:-255.0,add:1 \
! tensor_filter framework=tensorrt model=nnstreamer/tests/test_models/models/lenet5.uff input=56:56:1 inputtype=float32 inputname="in"  output=10 outputtype=float32 outputname=out \
! tensor_decoder mode=image_labeling option1=nnstreamer/tests/test_models/labels/lenet_label.txt \
! filesink location=test_log.txt**

Running the script above should output the same error.
The original property 'input' of 'tensor_filter' is '**input=28:28:1**' in 'runTest.sh'. 
When 'input' is set as it was originally, the pipeline outputs:
(gst-launch-1.0:4789): GLib-CRITICAL **: 10:13:37.302: g_string_insert_len: assertion 'len == 0 || val != NULL' failed
(gst-launch-1.0:4789): GLib-CRITICAL **: 10:13:37.303: g_string_insert_len: assertion 'len == 0 || val != NULL' failed
(gst-launch-1.0:4789): GLib-CRITICAL **: 10:13:37.303: g_string_insert_len: assertion 'len == 0 || val != NULL' failed
(gst-launch-1.0:4789): GLib-CRITICAL **: 10:13:42.398: g_string_insert_len: assertion 'len == 0 || val != NULL' failed
(gst-launch-1.0:4789): GLib-CRITICAL **: 10:13:42.398: g_string_insert_len: assertion 'len == 0 || val != NULL' failed
(gst-launch-1.0:4789): GLib-CRITICAL **: 10:13:42.398: g_string_insert_len: assertion 'len == 0 || val != NULL' failed
(gst-launch-1.0:4789): GLib-CRITICAL **: 10:13:42.399: g_string_insert_len: assertion 'len == 0 || val != NULL' failed
(gst-launch-1.0:4789): GLib-CRITICAL **: 10:13:42.399: g_string_insert_len: assertion 'len == 0 || val != NULL' failed
Setting pipeline to PAUSED ...
Pipeline is PREROLLING ...
(gst-launch-1.0:4789): GLib-CRITICAL **: 10:13:42.402: g_string_insert_len: assertion 'len == 0 || val != NULL' failed
(gst-launch-1.0:4789): GLib-CRITICAL **: 10:13:42.402: g_string_insert_len: assertion 'len == 0 || val != NULL' failed
** (gst-launch-1.0:4789): CRITICAL **: 10:13:42.403: gst_pad_set_caps: assertion 'caps != NULL && gst_caps_is_fixed (caps)' failed
(gst-launch-1.0:4789): GStreamer-CRITICAL **: 10:13:42.403: gst_mini_object_unref: assertion 'mini_object != NULL' failed
ERROR: from element /GstPipeline:pipeline0/GstTensorMerge:m: GStreamer error: negotiation problem.
Additional debug info:
/home/edgeai/nnstreamer/gst/nnstreamer/tensor_merge/gsttensormerge.c(631): gst_tensor_merge_set_src_caps (): /GstPipeline:pipeline0/GstTensorMerge:m
ERROR: pipeline doesn't want to preroll.
Setting pipeline to NULL ...
Freeing pipeline ...

I think the correct input of 'lenet5.uff' should be 28:28:1. But since the input of 'tensor_filter' is **'28:28:1:2'**, I have no idea how to set the **'input'** and **'output'** properties.
I also read the 'tensor_filter_tensorrt.cc' code about how to invoke TensorRT engine in the sub-plugin. Could it be relevant to the code as below?
**'builder->setMaxBatchSize (1);'**
Maybe the argument passed to setMaxBatchSize() should be dynamic? In this case should it be 2?

Thank you!

**Comment by myungjoo** [comment] 2022-07-29 04:42
> I think the correct input of 'lenet5.uff' should be 28:28:1. But since the input of 'tensor_filter' is '28:28:1:2', I have no idea how to set the 'input' and 'output' properties.

You need to let me understand what you are actually doing.

Do you want to infer the merged picture of the to images? or do you want to infer each picture independently and sequentially?

tensor-merge of two 28:28 can become one of the following four dimensions, depending on option: ```56:28``, ```28:56```, ```28:28:2```, or ```28:28:1:2```. I thought you were merging the data, not only the streams.

If you want to infer ```28:28``` twice from these two, you should NOT merge, mux, or aggregate the input frames. (merging streams, but not merging data)
In such a case, you can use join. From two streams of ```28:28, framerate = 30fps```, it will generate ```28:28, framerate = 60fps```.

**Comment by KurtKoo** [comment] 2022-07-29 05:49
> > I think the correct input of 'lenet5.uff' should be 28:28:1. But since the input of 'tensor_filter' is '28:28:1:2', I have no idea how to set the 'input' and 'output' properties.
> 
> You need to let me understand what you are actually doing.
> 
> Do you want to infer the merged picture of the to images? or do you want to infer each picture independently and sequentially?
> 
> tensor-merge of two 28:28 can become one of the following four dimensions, depending on option: `56:28`, `28:56`, `28:28:2`, or `28:28:1:2`. I thought you were merging the data, not only the streams.
> 
> If you want to infer `28:28` twice from these two, you should NOT merge, mux, or aggregate the input frames. (merging streams, but not merging data) In such a case, you can use join. From two streams of `28:28` (n frames from stream 1, m frames from stream 2) , it will generate `28:28` (n+m frames as output).

Sorry about not making it clear.
Yes, using 'join' enables the pipeline to infer 28:28 **twice** sequentially.

 I want the pipeline to infer 28:28 **once** from these two in a parallel way. Is this possible?

Thank you.

**Comment by myungjoo** [comment] 2022-08-01 02:56
>  a parallel way

do you want
```
input1 ! tensor_filter ! output1
input2 ! tensor_filter ! output2
```
?

If you simply want to process two different input streams in parallel, you can just have them as above.

If you want to "join" the output:
```
input1 ! tensor_filter ! m.
input2 ! tensor_filter ! m.
join name=m ! output
```

**Comment by KurtKoo** [comment] 2022-08-01 11:48
I'm trying to deploy NNStreamer on Jetson TX2. I am wondering how to combine multiple input stream as 1 tensor for the model so that the device can process multiple data every inference. That's why I want to do it in parallel.

`input1 ! tensor_filter ! output1
input2 ! tensor_filter ! output2`
Pipeline like this runs successfully with image input. But when the input is video stream, it outputs **'CAUGHT SIGSEGV'**.
`gst-launch-1.0` filesrc location=number_1_28x28_25fps.mp4 ! qtdemux ! h264parse ! nvv4l2decoder \
       ! nvvidconv ! 'video/x-raw,format=GRAY8,width=2560,height=1440,framerate=25/1' \
       ! videoscale ! 'video/x-raw,width=28,height=28' \
       ! tensor_converter input-type=uint8 \
       ! tensor_transform mode=transpose option=1:2:0:3 ! tensor_transform mode=arithmetic option=typecast:float32,div:-255.0,add:1 \
       ! tensor_filter framework=tensorrt model=models/lenet5.uff input=28:28:1 inputtype=float32 inputname="in"  output=10 outputtype=float32 outputname=out \
       ! tensor_decoder mode=image_labeling option1=labels/lenet_label.txt ! filesink location=log_1.txt \
         filesrc location=number_9_28x28_25fps.mp4 ! qtdemux ! h264parse ! nvv4l2decoder \
       ! nvvidconv ! 'video/x-raw,format=GRAY8,width=2560,height=1440,framerate=25/1' \
       ! videoscale ! 'video/x-raw,width=28,height=28' \
       ! tensor_converter input-type=uint8 \
       ! tensor_transform mode=transpose option=1:2:0:3 ! tensor_transform mode=arithmetic option=typecast:float32,div:-255.0,add:1 \
       ! tensor_filter framework=tensorrt model=models/lenet5.uff input=28:28:1 inputtype=float32 inputname="in"  output=10 outputtype=float32 outputname=out \
       ! tensor_decoder mode=image_labeling option1=labels/lenet_label.txt ! filesink `location=log_9.txt`

I also tried **join**. But I read the desription saying **the input streams should not operate at the same time**. And my inputs were fixed to 25 fps at first. The **'join'** pipeline hanged after several inference, which I guess it was because of the reason in the description. It also hanged even if I slowed down the framerate of one input.

I want the device to run infernce on (batch, channel, height, width) and the batch is larger than 1. Maybe I should write a subplugin.

Thank you!

**Comment by myungjoo** [comment] 2022-08-02 09:22
I still don't understand your intention or your requirement here.

If you want to combine data frames into a single data frame, having "batch > 1", it is NEVER going to be 28:28. It's going to be 28:28:m or 28:28:1:m (m>1), which is to "process multiple data every inference" (merge or aggregate depending on stream topology.)

But, in the previous message, you want to keep "28:28", not "28:28:m, m>1", which means you are going to process multiple data with multiple inferences. (join)

If the former is right (as in your message of today), you still don't need anything you. You can keep using tensor_merge or tensor_aggregate.

If the latter is right (as in your message of a few days ago), you are going to use join or multiple pipelines. However, if it gets SIGSEGV, it means that both tensor-rt (NVidia's) and nnstreamer-tensorrt (ours) are not thread-safe. (if either of it is thread-safe, it should work).

Anyway... note that all the three approaches ( option1. batch > 1 / option2a. join / option2b. multi-stream ) should have similar performance.... unless you have multiple independent GPUs installed (which Jeston cannot have), with different neural nets dedicated to each GPU. Your GPU will only accept SINGLE task at a time, requesting multiple tasks into a GPU will only cause problems as you are witnessing right now. You may get performance gain if your networks are way too light... too light to fill the pipeline... but in such cases, you usually don't need performance gain.

**Comment by KurtKoo** [comment] 2022-08-03 01:48
Great help! **Join** will meet the need.

```
gst-launch-1.0 filesrc location=number_1_28x28_25fps.mp4 ! qtdemux ! h264parse ! nvv4l2decoder \
       ! nvvidconv ! 'video/x-raw,format=GRAY8,width=2560,height=1440,framerate=25/1' \
       ! videoscale ! 'video/x-raw,width=28,height=28' \
       ! tensor_converter input-type=uint8 \
       ! queue ! j.sink_0 \
         filesrc location=number_9_28x28_25fps.mp4 ! qtdemux ! h264parse ! nvv4l2decoder \
       ! nvvidconv ! 'video/x-raw,format=GRAY8,width=2560,height=1440,framerate=25/1' \
       ! videoscale ! 'video/x-raw,width=28,height=28' \
       ! tensor_converter input-type=uint8 \
       ! j.sink_1 join name=j ! queue \
       ! tensor_transform mode=transpose option=1:2:0:3 ! tensor_transform mode=arithmetic option=typecast:float32,div:-255.0,add:1 ! queue \
       ! tensor_filter framework=tensorrt model=models/lenet5.uff input=28:28:1 inputtype=float32 inputname="in"  output=10 outputtype=float32 outputname=out \
       ! tensor_decoder mode=image_labeling option1=labels/lenet_label.txt ! filesink location=log.txt
```

Pipeline with script above works. However, there are never 2000 results in the 'log.txt' since each video contains 1000 frames and the number of results varies among each inference but never 2000.
Some frames dropped?

Thank you!

**Comment by myungjoo** [comment] 2022-08-03 05:53
Maybe it cannot process 50 frames per second. I'd recommend processing them in "batch processing" (slow down input feeds if processing slowly), not "real-time processing (enforcing to feed 25 frames/s from each input).

I'd recommend trying:
1. ```sync=false``` at filesink so that it won't try to be at a designated framerate
2. don't enforce framerate
3. review the log (enable gst log). it will show which element is dropping frames.

The recommendation 1 will generally solve the issue.

**Comment by KurtKoo** [comment] 2022-08-07 05:01
I have solved the problem by using join element(**multiple input<->one tensor_filter**) or the method you proposed before(**multi input<->multiple tensor_filter**).  
Grateful for your help!

And both solutions have been tested successfully on Jetson Orin platform after I modified the source code. Crash like "SIGSEGV"(occured in TX2 every time in the "multiple input<->multiple tensor_filter" case) never happened again. Possible to have a bug in the "invoke" function in "tensor_filter_tensorrt.cc"？ How could I report a bug？

By the way, are the plugins of NNStreamer designed to drop frames when the elements(converter, join, mux, transform, filter and decoder) are receiving too many frames?

Thanks.

**Comment by myungjoo** [comment] 2022-08-08 09:46
> I have solved the problem by using join element(multiple input<->one tensor_filter) or the method you proposed before(multi input<->multiple tensor_filter).
> Grateful for your help!

Glad that it helped!


> Crash like "SIGSEGV"(occured in TX2 every time in the "multiple input<->multiple tensor_filter" case) never happened again. Possible to have a bug in the "invoke" function in "tensor_filter_tensorrt.cc"？ How could I report a bug？

You may create an issue with a minimal pipeline description that recreates the behavior (SIGSEGV) with enough information so that other developers can generate the same issue without much effort.


> By the way, are the plugins of NNStreamer designed to drop frames when the elements(converter, join, mux, transform, filter and decoder) are receiving too many frames?

In general, gstreamer framework itself (and its base plugins) will do it. You can use queue (w/ some options) to control such behaviors.

**Comment by myungjoo** [comment] 2022-08-08 09:46
Closing the issue because the mentions issue is resolved.

**Closed by myungjoo** 2022-08-08 09:46 UTC
