### ISSUE TITLE
How to use tensor_mux correctly

### ISSUE THREAD

**Issue by yancaoweidaode** [nnstreamer/nnstreamer#4160] opened 2023-07-19 06:41 UTC
I tried to merge two rtsp video streams into a single stream using tensor_mux and then use tensor_filter to perform inference on the data. I used the following pipeline  "gst-launch-1.0 \
rtspsrc location=rtsp://path1 latency=100 ! queue ! rtph264depay ! h264parse ! avdec_h264  ! videoconvert ! videoscale ! video/x-raw,height=320,width=544,format=BGR ! tensor_converter ! tensor_transform mode=typecast option=float32 ! tensor_transform mode=dimchg option=0:2 ! mux.sink_0 \
rtspsrc location=rtsp://path2 latency=100 ! queue ! rtph264depay ! h264parse ! avdec_h264  ! videoconvert ! videoscale ! video/x-raw,height=320,width=544,format=BGR ! tensor_converter ! tensor_transform mode=typecast option=float32 ! tensor_transform mode=dimchg option=0:2 ! mux.sink_1 \
tensor_mux name=mux ! tensor_filter framework=openvino model=/opt/intel/openvino_2023.0.0.10926/models_ir/intel/person-detection-retail-0013/FP32/person-detection-retail-0013.xml accelerator=true:cpu  ! fakesink", but got the following error "from element /GstPipeline:pipeline0/GstTensorFilter:tensorfilter0: gst_tensor_filter_configure_tensor:1008 The input tensor of tensor_filter (openvino:/opt/intel/openvino_2023.0.0.10926/models_ir/intel/person-detection-retail-0013/FP32/person-detection-retail-0013.xml) is not compatible with the configured input information. Please check tensor-filter properties if you have given input dimensions explicitly; or the model properties if you have not given them. Check the input stream caps and related caps-filters, too. The given gstcap is other/tensors, format=(string)static, num_tensors=(int)2, framerate=(fraction)0/1, dimensions=(string)"544:320:3:1:1:1:1:1\,544:320:3:1:1:1:1:1", types=(string)"float32\,float32", which is not compatible:  0 : float32 [544:320:3:1:1:1:1:1] | float32 [544:320:3:1:1:1:1:1] 
 1 : float32 [544:320:3:1:1:1:1:1] | None Not equal"How should I solve this problem

**Comment by yancaoweidaode** [comment] 2023-07-19 06:47
I tried another pipeline"gst-launch-1.0 \
rtspsrc location=rtsp://admin:aIlab1234@10.110.131.12 latency=100 ! queue ! rtph264depay ! h264parse ! avdec_h264  ! videoconvert ! videoscale ! video/x-raw,height=320,width=544,format=BGR ! tensor_converter ! tensor_transform mode=typecast option=float32 ! tensor_transform mode=dimchg option=0:2 ! mux.sink_0 \
rtspsrc location=rtsp://admin:aIlab1234@10.110.131.13 latency=100 ! queue ! rtph264depay ! h264parse ! avdec_h264  ! videoconvert ! videoscale ! video/x-raw,height=320,width=544,format=BGR ! tensor_converter ! tensor_transform mode=typecast option=float32 ! tensor_transform mode=dimchg option=0:2 ! mux.sink_1 \
tensor_mux name=mux ! tensor_filter framework=openvino model=/opt/intel/openvino_2023.0.0.10926/models_ir/intel/person-detection-retail-0013/FP32/person-detection-retail-0013.xml accelerator=true:cpu input=544:320:3,544:320:3 inputtype=float32 ! fakesink", but the error message was the same

**Comment by yancaoweidaode** [comment] 2023-07-19 06:51
The pipeline of single stream is ok, this pipeline is "gst-launch-1.0 rtspsrc location=rtsp://admin:aIlab1234@10.110.131.12 latency=100 ! queue ! rtph264depay ! h264parse ! avdec_h264  ! videoconvert ! videoscale ! video/x-raw,height=320,width=544,format=BGR ! tensor_converter ! tensor_transform mode=typecast option=float32 ! tensor_transform mode=dimchg option=0:2 ! tensor_filter framework=openvino model=/opt/intel/openvino_2023.0.0.10926/models_ir/intel/person-detection-retail-0013/FP32/person-detection-retail-0013.xml accelerator=true:cpu ! tensor_decoder mode=bounding_boxes option1=ov-person-detection option4=640:480 option5=300:300 ! videoconvert ! x264enc ! rtspclientsink location=rtsp://10.110.159.4:30217/live/79L5 protocols=tcp"

**Comment by gichan-jang** [comment] 2023-07-19 07:20
What is the purpose of merging stream from two rtspsrc?
Do you want to use the currently available sources?
Tensor-mux combine two single tensor (one buffer, one memory) into one tensors (One buffer, multiple memories).
As you used, the model receives single tensor stream as the input.
If you want to do inference from multiple rtspsrc from one model, try to use join.
```
"gst-launch-1.0 \
rtspsrc location=rtsp://path1 latency=100 ! queue ! rtph264depay ! h264parse ! avdec_h264 ! videoconvert ! videoscale ! video/x-raw,height=320,width=544,format=BGR ! tensor_converter ! tensor_transform mode=typecast option=float32 ! tensor_transform mode=dimchg option=0:2 ! join.sink_0 \
rtspsrc location=rtsp://path2 latency=100 ! queue ! rtph264depay ! h264parse ! avdec_h264 ! videoconvert ! videoscale ! video/x-raw,height=320,width=544,format=BGR ! tensor_converter ! tensor_transform mode=typecast option=float32 ! tensor_transform mode=dimchg option=0:2 ! join.sink_1 \
join name=join ! tensor_filter framework=openvino model=/opt/intel/openvino_2023.0.0.10926/models_ir/intel/person-detection-retail-0013/FP32/person-detection-retail-0013.xml accelerator=true:cpu ! fakesink"
```

**Comment by yancaoweidaode** [comment] 2023-07-19 07:47
Using pipeline 
`"gst-launch-1.0 \
rtspsrc location=rtsp://path1 latency=100 ! queue ! rtph264depay ! h264parse ! avdec_h264 ! videoconvert ! videoscale ! video/x-raw,height=320,width=544,format=BGR ! tensor_converter ! tensor_transform mode=typecast option=float32 ! tensor_transform mode=dimchg option=0:2 ! join.sink_0 \
rtspsrc location=rtsp://path2 latency=100 ! queue ! rtph264depay ! h264parse ! avdec_h264 ! videoconvert ! videoscale ! video/x-raw,height=320,width=544,format=BGR ! tensor_converter ! tensor_transform mode=typecast option=float32 ! tensor_transform mode=dimchg option=0:2 ! join.sink_1 \
join name=join ! tensor_filter framework=openvino model=/opt/intel/openvino_2023.0.0.10926/models_ir/intel/person-detection-retail-0013/FP32/person-detection-retail-0013.xml accelerator=true:cpu ! fakesink"`
, only path1 detection results can be seen by pulling the video stream using vlc. And, if you use a join, how do you separate the final detections

**Comment by gichan-jang** [comment] 2023-07-19 07:56
You can't distinguish where the result came from by using the join. If you want to distinguish the results, use 2 tensor filters. 
Please explain the scenario you want to do.

**Comment by yancaoweidaode** [comment] 2023-07-19 08:01
My scenario is to use an inference model that processes multiple rtsp video streams at the same time and then outputs the processed video streams to different rtsp servers

**Comment by yancaoweidaode** [comment] 2023-07-19 08:12
> What is the purpose of merging stream from two rtspsrc? Do you want to use the currently available sources? Tensor-mux combine two single tensor (one buffer, one memory) into one tensors (One buffer, multiple memories). As you used, the model receives single tensor stream as the input. If you want to do inference from multiple rtspsrc using one model, try to use join.
> 
> ```
> "gst-launch-1.0 \
> rtspsrc location=rtsp://path1 latency=100 ! queue ! rtph264depay ! h264parse ! avdec_h264 ! videoconvert ! videoscale ! video/x-raw,height=320,width=544,format=BGR ! tensor_converter ! tensor_transform mode=typecast option=float32 ! tensor_transform mode=dimchg option=0:2 ! join.sink_0 \
> rtspsrc location=rtsp://path2 latency=100 ! queue ! rtph264depay ! h264parse ! avdec_h264 ! videoconvert ! videoscale ! video/x-raw,height=320,width=544,format=BGR ! tensor_converter ! tensor_transform mode=typecast option=float32 ! tensor_transform mode=dimchg option=0:2 ! join.sink_1 \
> join name=join ! tensor_filter framework=openvino model=/opt/intel/openvino_2023.0.0.10926/models_ir/intel/person-detection-retail-0013/FP32/person-detection-retail-0013.xml accelerator=true:cpu ! fakesink"
> ```
I want to know, how does tensor_filter handle input from ther/tensors,num_tensors=2

**Comment by gichan-jang** [comment] 2023-07-19 08:13
> I want to know, how does tensor_filter handle input from ther/tensors,num_tensors=2

It depends on the model not tensor_filter.

**Comment by yancaoweidaode** [comment] 2023-07-19 08:18
> > I want to know, how does tensor_filter handle input from ther/tensors,num_tensors=2
> 
> It depends on the model not tensor_filter.
Does this mean that the model should have two input tensors?

**Comment by gichan-jang** [comment] 2023-07-19 08:20
> My scenario is to use an inference model that processes multiple rtsp video streams at the same time and then outputs the processed video streams to different rtsp servers

Why don't you use two tensor filters or two pipelines? What is the important relationship between the two rtspsrcs?
Do you make a panoramic video from two video srcs?

**Comment by gichan-jang** [comment] 2023-07-19 08:23
> I want to know, how does tensor_filter handle input from ther/tensors,num_tensors=2
> > It depends on the model not tensor_filter.
> > > Does this mean that the model should have two input tensors?

Right. `person-detection-retail-0013.xml` model receives a single tensor as the input.

**Comment by yancaoweidaode** [comment] 2023-07-19 08:47
> > > > put tensors?
> 
> Right. `person-detection-retail-0013.xml` model receives

I see , Is there any way I can convert the other/tensors num_tensors=2 to a other/tensor num_tensor=1 with a value of 2 in the batch dimension

**Comment by yancaoweidaode** [comment] 2023-07-19 08:48
> > My scenario is to use an inference model that processes multiple rtsp video streams at the same time and then outputs the processed video streams to different rtsp servers
> 
> Why don't you use two tensor filters or two pipelines? What is the important relationship between the two rtspsrcs? Do you make a panoramic video from two video srcs?



> > My scenario is to use an inference model that processes multiple rtsp video streams at the same time and then outputs the processed video streams to different rtsp servers
> 
> Why don't you use two tensor filters or two pipelines? What is the important relationship between the two rtspsrcs? Do you make a panoramic video from two video srcs?

This required me to start two separate processes and load the model twice, taking up additional resources

**Comment by myungjoo** [comment] 2023-07-20 05:59
If you want to accept two different sources for a single tensor-filter and have them fed to different outputs; e.g.,
```
src1 --+                     +--> sink1
       +--> tensor_filter -->+
src2 --+                     +--> sink2
```

, you need to let a buffer going through tensor_filter have a source-related metadata (which source is this coming from).

You can achieve it by using tensor_query;

server-side:
```
tensor-query-server-src --> tensor_filter --> tensor-query-server-sink
```
(multiple) client-side:
```
... --> tensor-query-client --> ...

```

**Comment by whcjb** [comment] 2023-07-21 03:15
i have the same requirment, could some one help. 

i want to use 8 rtsp to concat each source frame to a 8-batch tensor which will be sent to deep model for inference.

i use tensor_mux, but find frames shift problem, for example, sink_0 has ths same content of sink_6, this problem occurs about 1 in 20 frames.

how can i debug this?

thanks

**Comment by yancaoweidaode** [comment] 2023-07-21 07:17
> i have the same requirment, could some one help.
> 
> i want to use 8 rtsp to concat each source frame to a 8-batch tensor which will be sent to deep model for inference.
> 
> i use tensor_mux, but find frames shift problem, for example, sink_0 has ths same content of sink_6, this problem occurs about 1 in 20 frames.
> 
> how can i debug this?
> 
> thanks
Does your model have 8 Tensors as input？

**Comment by whcjb** [comment] 2023-07-21 09:06
yes，it can infer multi batch.
the problem is before inference. when tensor_mux concat the multi frames, that the buf may error shift.

**Comment by yancaoweidaode** [comment] 2023-07-21 09:56
> yes，it can infer multi batch. the problem is before inference. when tensor_mux concat the multi frames, that the buf may error shift.

this linke may help you https://github.com/nnstreamer/nnstreamer/issues/3854

**Comment by yancaoweidaode** [comment] 2023-07-21 09:59
> yes，it can infer multi batch. the problem is before inference. when tensor_mux concat the multi frames, that the buf may error shift.

but i have a question. the output of tensor_mux is other/tensors num=8, how did you tansform it to other/tensor num=1 batch_size=8?

**Comment by whcjb** [comment] 2023-07-21 11:12
thanks, i have rewrite some code, remove tensor format info, the collectpad will concat the sink buffer and then push to srcpad.

**Comment by gichan-jang** [comment] 2023-07-24 03:44
> > > > > put tensors?
> > 
> > 
> > Right. `person-detection-retail-0013.xml` model receives
> 
> I see , Is there any way I can convert the other/tensors num_tensors=2 to a other/tensor num_tensor=1 with a value of 2 in the batch dimension

Batch interference is not supported by nnstreamer now. To support that, tensor_filter should be changed.

**Comment by myungjoo** [comment] 2023-07-24 06:06
> > yes，it can infer multi batch. the problem is before inference. when tensor_mux concat the multi frames, that the buf may error shift.
> 
> but i have a question. the output of tensor_mux is other/tensors num=8, how did you tansform it to other/tensor num=1 batch_size=8?

Use tensor_merge.

It can do N:M:L:1 num_tensor=8 into N:M:L:8.

**Comment by gichan-jang** [comment] 2023-07-26 10:25
> Batch interference is not supported by nnstreamer now. To support that, tensor_filter should be changed.

I'm sorry, I gave the wrong answer to this. I checked batch inference worked well in NNStreamer. I testes it with yolov5 model.
Please check this pipeline.
```
gst-launch-1.0 \
  filesrc location=${PATH_TO_IMAGE_1} ! pngdec ! videoscale ! imagefreeze ! videoconvert ! videoscale ! \
    video/x-raw,width=320,height=320,format=RGB,pixel-aspect-ratio=1/1,framerate=30/1 ! tensor_converter ! \
    tensor_transform mode=transpose option=1:2:0:3 ! \
    tensor_transform mode=arithmetic option=typecast:float32,div:255.0 ! m.sink_0 \
  filesrc location=${PATH_TO_IMAGE_2} ! pngdec ! videoscale ! imagefreeze ! videoconvert ! videoscale ! \
    video/x-raw,width=320,height=320,format=RGB,pixel-aspect-ratio=1/1,framerate=30/1 ! tensor_converter ! \
    tensor_transform mode=transpose option=1:2:0:3 ! \
    tensor_transform mode=arithmetic option=typecast:float32,div:255.0 ! m.sink_1 \
  tensor_merge name=m mode=linear option=3 sync-mode=basepad ! \
    tensor_filter framework=pytorch model=yolov5s.torchscript input=320:320:3:2 inputtype=float32 output=85:6300:1:2 outputtype=float32 latency=1 ! \
  tensor_split name=s tensorseg=85:6300:1:1,85:6300:1:1 \
    s.src_0 ! queue ! tensor_decoder mode=bounding_boxes option1=yolov5 option2=coco.txt option3=1 option4=1000:1000 option5=320:320 ! \
    video/x-raw,width=1000,height=1000,format=RGBA ! videoconvert ! ximagesink \
    s.src_1 ! queue ! tensor_decoder mode=bounding_boxes option1=yolov5 option2=coco.txt option3=1 option4=1000:1000 option5=320:320 ! \
    video/x-raw,width=1000,height=1000,format=RGBA ! videoconvert ! ximagesink
```

**Comment by myungjoo** [comment] 2023-07-28 09:22
> Batch interference is not supported by nnstreamer now. To support that, tensor_filter should be changed.

**Correction**: we assumed to have a single batch for inferences when we designed nnstreamer. However, this design does NOT prohibit multi-batch inferences. You can do it by simply designating a rank of a tensor dimension as a batch and applying a model/framework that shares the same batch designation.

**Comment by myungjoo** [comment] 2023-07-28 09:25
> idth=320,height=320,format=RGB,pixel-aspect-ratio=1/1,framerate=30/1 ! tensor_converter ! \
>     tensor_transform mode=transpose option=1:2:0:3 ! \
>     tensor_transform mode=arithmetic option=typecast:float32,div:255.0 ! m.sink_

That pipeline looks legit. So.. does this work appropriately?

**Comment by myungjoo** [comment] 2023-10-13 08:57
Without further interactions for months, I'm closing this.

**Closed by myungjoo** 2023-10-13 08:57 UTC
