### ISSUE TITLE
Yolov4 model incorrect output using tensor_filter vivante in  nnstremer-private-plugin 

### ISSUE THREAD

**Issue by abhajaswal** [nnstreamer/nnstreamer#3315] opened 2021-06-01 10:10 UTC
# Issue Description

OS - Tizen 6.0 

I am trying to use the network binary for yolov4 model using tensor_filter vivante in  nnstremer-private-plugin 
Input  required for this model is RGB data , in NCHW format as per the the requirement for model

RRRGGGBBB format

Reference vnn C code is as below :
    /*-----------------------------------------
          Tensor initialize
     -----------------------------------------*/
    attr.dtype.fmt = VSI_NN_DIM_FMT_NCHW;
    /* @input_0:out0 */
    attr.size[0] = 416;
    attr.size[1] = 416;
    attr.size[2] = 3;
    attr.size[3] = 1;
    attr.dim_num = 4;
    attr.dtype.scale = 0.00390625;
    attr.dtype.zero_point = 0;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_AFFINE_ASYMMETRIC;
    NEW_NORM_TENSOR(norm_tensor[0], attr, VSI_NN_TYPE_UINT8);

   sz = vsi_nn_GetElementNum(tensor);
    data = (uint8_t*)malloc(sz * sizeof(uint8_t));

    memset(&meta, 0, sizeof(vnn_input_meta_t));
    meta.image.preprocess[0] = VNN_PREPRO_REORDER;
    meta.image.preprocess[1] = VNN_PREPRO_MEAN;
    meta.image.preprocess[2] = VNN_PREPRO_SCALE;
    meta.image.reorder[0] = 0;
    meta.image.reorder[1] = 1;
    meta.image.reorder[2] = 2;
    meta.image.mean[0] = 0.0f;
    meta.image.mean[1] = 0.0f;
    meta.image.mean[2] = 0.0f;
    meta.image.scale = 0.003921569;

_data_transform  C code --> converts to NCHW format and this model works fine !!

    for (int i = 0; i < _cnt_of_array(meta.image.preprocess); i++)
    {
        switch (meta.image.preprocess[i])
        {
            case VNN_PREPRO_NONE:
                break;
            case VNN_PREPRO_REORDER:
                _data_transform(idata, data, &meta, tensor);
                break;
            default:
                break;
        }
    }

I used the Yolov3 sample nnstreamline pipeline example for reference ! 

I want to replicate C code of yolov4 model  output  using nnstreamer pipeline -> so i gave below command which is succesful in execution

gst-launch-1.0 filesrc location=sample_horses_416x416.jpg ! \
jpegdec ! videoconvert ! video/x-raw,format=RGB,width=416,height=416 ! \
tensor_converter ! tensor_transform mode=transpose option=1:2:0:3 ! \
tensor_filter framework=vivante model="yolo-v4.nb,libvnn-yolo-v4.so" custom=pp ! \
filesink location=vivante.out.bin

But the output of this is little bit different as per the C code.

Can you let me know the buffer layout for tensor_convertor  as per readme.md it provide output as CWHN forrmat
tensor_transform 1:2:0:3  would convert this to WHCN format  .

As per logs also its tensor_convertor  src caps : 
/GstPipeline:pipeline0/GstTensorConverter:tensorconverter0.GstPad:src: caps = other/tensor, framerate=(fraction)0/1, dimension=(string)3:416:416:1, type=(string)uint8 
and

/GstPipeline:pipeline0/GstTensorTransform:tensortransform0.GstPad:src: caps = other/tensor, framerate=(fraction)0/1, dimension=(string)416:416:3:1, type=(string)uint8

Although C code was making the input order as NCHW then also this is correct !!

So I am confused with input Buffer Layout handing in to NPU using nnstreamer !! 

Is there any way to get exact similar output as C code for using nnstreamer ?

**Comment by abhajaswal** [comment] 2021-06-01 12:36
for example for inceptionV4 model model also my output comes incorrect

gst-launch-1.0 -v filesrc location=ample_pizza_299x299.jpg ! jpegdec ! videoconvert ! video/x-raw,format=RGB,\
width=299,height=299 ! tensor_converter \
! tensor_filter framework=vivante model="/usr/share/dann/inception-v4.nb,/usr/lib64/libvnn-inception-v4.so" custom=pp ! filesink location=vivante.out.bin

/*-----------------------------------------
  Tensor initialize
 -----------------------------------------*/
    attr.dtype.fmt = VSI_NN_DIM_FMT_NCHW;
    /* @attach_InceptionV4/Logits/Predictions:out0 */
    attr.size[0] = 101;
    attr.size[1] = 1;
    attr.dim_num = 2;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_NONE;
    NEW_NORM_TENSOR(norm_tensor[0], attr, VSI_NN_TYPE_FLOAT16);

    /* @attach_input/out0_1:out0 */
    attr.size[0] = 3;
    attr.size[1] = 299;
    attr.size[2] = 299;
    attr.size[3] = 1;
    attr.dim_num = 4;
    attr.dtype.scale = 0.0078125;
    attr.dtype.zero_point = 128;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_AFFINE_ASYMMETRIC;
    NEW_NORM_TENSOR(norm_tensor[1], attr, VSI_NN_TYPE_UINT8);

**Comment by anyj0527** [comment] 2021-06-02 01:51
I've never use vivante..., but you may check this nnstreamer example which uses vivante yolo3 model:
https://github.com/nnstreamer/nnstreamer-example/tree/main/Tizen.platform/Vivante_pipeline_NonGUI_yoloV3

**Comment by myungjoo** [comment] 2021-06-02 03:06
> I've never use vivante..., but you may check this nnstreamer example which uses vivante yolo3 model:
> https://github.com/nnstreamer/nnstreamer-example/tree/main/Tizen.platform/Vivante_pipeline_NonGUI_yoloV3

This probably has no relation with Vivante H/W itself. If there is an issue, it would probably be input image/tensor formats.

**Comment by myungjoo** [comment] 2021-06-02 03:10
> Although C code was making the input order as NCHW then also this is correct !!
So I am confused with input Buffer Layout handing in to NPU using nnstreamer !!
Is there any way to get exact similar output as C code for using nnstreamer ?

You need to re-order / convert data format as what your model wants.

If videoconvert's possible results (look at GStreamer manual for detail) don't fit your needs,
you can use tensor-transform to further re-format the data. What's the byte-format required by your model? Do you need normalization?

**Comment by abhajaswal** [comment] 2021-06-02 10:13
For both models yolov4 and inceptionv4  input type  is unsigned char.  Since data is unit8 it does not need to normalize and quantize it.

For yolov4 model the input should be RRRR.. GGGG.. BBB.. FORMAT.. which is similar to yolov3 example  where data is BBBBB..GGGGG..RRRR FORMAT I,e NCHW FORMAT  3x416x416  


Inception v4 MODEL I use  is similar to Inceptionv3 model example!! Data type is uint8 and input format is NHWC I,E RGBRGBRGB...  When the example for nnstreamer INCEPTIONV3  was tested  it gave  similar results as that of reference C Code?

**Comment by myungjoo** [comment] 2021-06-04 01:47
If each byte goes RRRR... GGGG... BBBB..., you need to apply transpose or dimchg.

You are feeding R G B R G B R G B ... with ``` ... videoconvert ! video/x-raw,format=RGB,
width=299,height=299 ! tensor_converter
! tensor_filter framework=vivante  ...```.

> Can you let me know the buffer layout for tensor_convertor as per readme.md it provide output as CWHN forrmat
tensor_transform 1:2:0:3 would convert this to WHCN format .

Yes, this is supposed to transform WHCN --> CWHN.

We have tested Yolo-v3 + Vivante last year, around March~April for customers.


The simplified code of it is at github.com/nnstreamer/nnstreamer-example.git / /Tizen.platform/Vivante_pipeline_NonGUI_yoloV3

>             _data_transform(idata, data, &meta, tensor);

I expect that with the data of ```meta``` ```_data_transform``` is applying a few arithmetic ops; 
```
memset(&meta, 0, sizeof(vnn_input_meta_t));
meta.image.preprocess[0] = VNN_PREPRO_REORDER;
meta.image.preprocess[1] = VNN_PREPRO_MEAN;
meta.image.preprocess[2] = VNN_PREPRO_SCALE;
meta.image.reorder[0] = 0;
meta.image.reorder[1] = 1;
meta.image.reorder[2] = 2;
meta.image.mean[0] = 0.0f;
meta.image.mean[1] = 0.0f;
meta.image.mean[2] = 0.0f;
meta.image.scale = 0.003921569;
```
You are definitely doing something with ```_data_transform``` and you need to understand what that does and express it with corresponding stream processor.

**Comment by myungjoo** [comment] 2021-08-02 03:20
As there is no follow-ups, assuming that the issue is resolved, I'm closing this.

**Closed by myungjoo** 2021-08-02 03:20 UTC
